-- MySQL Script generated by MySQL Workbench
-- 08/22/16 18:43:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema transnow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transnow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transnow` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `transnow` ;

-- -----------------------------------------------------
-- Table `transnow`.`lang_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transnow`.`lang_type` (
  `code` VARCHAR(10) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transnow`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transnow`.`article` (
  `input_text` VARCHAR(128) NOT NULL,
  `last_lookup_date` DATETIME NULL,
  `lookup_qty` INT NULL,
  `article` TEXT(65535) NULL,
  `lang_type_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`input_text`, `lang_type_code`),
  INDEX `fk_article_lang_type1_idx` (`lang_type_code` ASC),
  UNIQUE INDEX `lookup_qty_UNIQUE` (`lookup_qty` ASC),
  CONSTRAINT `fk_article_lang_type1`
    FOREIGN KEY (`lang_type_code`)
    REFERENCES `transnow`.`lang_type` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transnow`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transnow`.`user` (
  `user` VARCHAR(100) NOT NULL,
  `reg_date` DATETIME NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transnow`.`lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transnow`.`lookup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(100) NOT NULL,
  `input_text` VARCHAR(128) NOT NULL,
  `lang_code` VARCHAR(10) NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`, `user`, `input_text`, `lang_code`),
  INDEX `fk_lookup_article1_idx` (`input_text` ASC),
  INDEX `fk_lookup_lang_type1_idx` (`lang_code` ASC),
  CONSTRAINT `fk_lookup_user`
    FOREIGN KEY (`user`)
    REFERENCES `transnow`.`user` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lookup_article1`
    FOREIGN KEY (`input_text`)
    REFERENCES `transnow`.`article` (`input_text`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lookup_lang_type1`
    FOREIGN KEY (`lang_code`)
    REFERENCES `transnow`.`lang_type` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
